name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "email"

[[kv_namespaces]]
binding = "kv"

[[r2_buckets]]
binding = "r2"
bucket_name = "email"

#[[send_email]]
#name = "email"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]


#[vars]
#ai_model = ""
#analysis_cache = false
#orm_log = false
#domain = []
#admin = admin@example.com
#jwt_secret = ""
#linuxdo_client_id = ""
#linuxdo_client_secret = ""
#linuxdo_callback_url = ""

[build]
command = "npm --prefix ../mail-vue run build"
